### ISSUE TITLE
Lesson_14._App_&amp;_Middleware_Setup

### ISSUE THREAD

**Issue by aadhar41** [aadhar41/nodeauth#1]
app.use(expressValidator({
        ^

TypeError: expressValidator is not a function
    at Object.<anonymous> (C:\xampp\htdocs\Projects\nodeauth\app.js:48:9)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\xampp\htdocs\Projects\nodeauth\bin\www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

**Comment by aadhar41** [comment]
Just run command to solve issue it is related with express-validator version
npm uninstall express-validator
npm install express-validator@5.3.0

**Comment by aadhar41** [comment]
https://stackoverflow.com/questions/56733975/express-validator-error-expressvalidator-is-not-a-function
